version: '3.7'

services:
  app:
    image: projectprimera/ongeki-score:local
    depends_on:
      - mariadb
      - redis
    ports:
      - '8000:80'
    volumes:
      - type: bind
        source: ./docker/.env
        target: /etc/.env
      - type: bind
        source: ./docker/nginx/conf.d/sample.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./docker/oauth-private.key
        target: /app/storage/oauth-private.key
      - type: bind
        source: ./docker/oauth-public.key
        target: /app/storage/oauth-public.key
      - type: bind
        source: ./OngekiScoreLog/app
        target: /app/app
      - type: bind
        source: ./OngekiScoreLog/bootstrap/app.php
        target: /app/bootstrap/app.php
      - type: bind
        source: ./OngekiScoreLog/config
        target: /app/config
      - type: bind
        source: ./OngekiScoreLog/database
        target: /app/database
      - type: bind
        source: ./OngekiScoreLog/public
        target: /app/public
      - type: bind
        source: ./OngekiScoreLog/resources
        target: /app/resources
      - type: bind
        source: ./OngekiScoreLog/routes
        target: /app/routes
      - type: bind
        source: ./OngekiScoreLog/storage/logs
        target: /app/storage/logs
      - type: bind
        source: ./OngekiScoreLog/tests
        target: /app/tests
      - type: bind
        source: ./OngekiScoreLog/artisan
        target: /app/artisan
      - type: bind
        source: ./OngekiScoreLog/server.php
        target: /app/server.php
    environment:
      ONGEKI_VERSION: 1
      ONGEKE_VERSION_DATE: "2000/01/01"
      IS_MAINTENANCE_API_USER_UPDATE: false
      APP_NAME: 'OngekiScoreLog(Local)'
      MIX_APP_NAME: "OngekiScoreLog(Local)"
      APP_ENV: 'debug'
      APP_DEBUG: 'true'
      APP_KEY: 'base64:MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA='
      APP_URL: 'http://localhost:8000'
      MIX_APP_URL: "http://localhost:8000"
      GITHUB_REPO_URL: "https://github.com/ProjectPrimera/ongeki-score"
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ongeki-score-local
      DB_USERNAME: root
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
  mariadb:
    image: mariadb:10.7.1
    ports:
      - '33060:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ongeki-score-local
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  mariadb-data:
    driver: 'local'
  redis-data:
    driver: 'local'
