<tr>
    <th>{{$title}}</th>
    <th>{{$genre}}</th>
    <th>{{$difficulty}}</th>
    <th>{{$level}}</th>
    <th>{{$fullBell}}</th>
    <th>{{$fullCombo}}</th>
    <th>{{$allBreak}}</th>
    <th>{{$battleRank}}</th>
    <th>{{$technicalRank}}</th>
    <th>{{$battleScore}}</th>
    <th>{{$overDamage}}</th>
    <th>{{$nextOverDamage}}</th>
    <th>{{$technicalHighScore}}</th>
    <th>{{$nextTechnicalScore}}</th>
    <th>{{$updatedAt}}</th>
</tr>