<tr>
    <th>{{$title}}</th>
    <th>{{$difficulty}}</th>
    <th>{{$level}}</th>
    <th>{{$fullBell}}</th>
    <th>{{$fullCombo}}</th>
    <th>{{$allBreak}}</th>
    <th>{{$technicalRank}}</th>
    <th>{{$technicalHighScore}}</th>
    <th>{{$nextTechnicalScore}}</th>
    <th>{{$updatedAt}}</th>
</tr>