<tr>
    <th>{{$title}}</th>
    <th>{{$difficulty}}</th>
    <th>{{$level}}</th>
    <th>{{$battleRank}}</th>
    <th>{{$battleScore}}</th>
    <th>{{$overDamage}}</th>
    <th>{{$nextOverDamage}}</th>
    <th>{{$updatedAt}}</th>
</tr>