<tr>
    <td>{{$title}}</td>
    <td>{{$genre}}</td>
    <td>{{$difficulty}}</td>
    <td>{{$level}}</td>
    <td>{{$fullBell}}</td>
    <td>{{$fullCombo}}</td>
    <td>{{$allBreak}}</td>
    <td>{{$battleRank}}</td>
    <td>{{$technicalRank}}</td>
    <td>{{$battleScore}}</td>
    <td>{{$overDamage}}</td>
    <td>{{$nextOverDamage}}</td>
    <td>{{$technicalHighScore}}</td>
    <td>{{$nextTechnicalScore}}</td>
    <td>{{$updatedAt}}</td>
</tr>