<tr>
    <td>{{$title}}</td>
    <td>{{$difficulty}}</td>
    <td>{{$level}}</td>
    <td>{{$fullBell}}</td>
    <td>{{$fullCombo}}</td>
    <td>{{$allBreak}}</td>
    <td>{{$technicalRank}}</td>
    <td>{{$technicalHighScore}}</td>
    <td>{{$nextTechnicalScore}}</td>
    <td>{{$updatedAt}}</td>
</tr>