<tr>
    <td>{{$title}}</td>
    <td>{{$difficulty}}</td>
    <td>{{$level}}</td>
    <td>{{$battleRank}}</td>
    <td>{{$battleScore}}</td>
    <td>{{$overDamage}}</td>
    <td>{{$nextOverDamage}}</td>
    <td>{{$updatedAt}}</td>
</tr>